server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    username: postgres
    password: postgres
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://78.24.220.57:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
