server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update # TODO make none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
