server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
#    url: jdbc:postgresql://192.168.50.87:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create # TODO make none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
