server:
  port: 8080
  error:
    include-message: always

spring:
  sql:
    init:
      encoding: UTF8
  datasource:
    username: postgres
#    password: postgres
    password: asldjk23
#    url: jdbc:postgresql://localhost:5432/postgres?characterEncoding=UTF-8
    url: jdbc:postgresql://78.24.220.57:5432/postgres?characterEncoding=UTF8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
