name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: build with gradle
        run: gradle clean build

      - name: build & push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: cteklo/kotlin-docker
          tags: ${{ github.run_number }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 149.154.64.151
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: echo 123
